#!/usr/bin/env php
<?php

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

$paths = [
    dirname(dirname(__DIR__)),
    dirname(__DIR__) . '/vendor',
    __DIR__ . '/vendor'
];

$loaded = false;
foreach ($paths as $path) {
    if (file_exists($path . '/autoload.php')) {
        require_once($path . '/autoload.php');
        $loaded = true;
        break;
    }
}

// Setup auto-loader.
$isComposerInstalled = true;
if (!$loaded) {
    require_once(__DIR__ . '/src/Loader.php');
    \CoRex\Command\Loader::initialize();
    $loaded = true;
    $isComposerInstalled = false;
}

try {
    $handler = new \CoRex\Command\Handler($argv, true, $isComposerInstalled);
    $handler->execute();
} catch (Exception $e) {
    print($e->getMessage() . "\n");
}
